version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/counter_app
    links:
      - db:postgres
    container_name: app_web_1
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    restart: always
    container_name: app_db_1
    ports:
      - "5432:5432"
    env_file:
      - .env
